### ISSUE TITLE
Impact reports PDF

### ISSUE THREAD

**Issue by toby-1-kenobi** [toby-1-kenobi/sag_reporter#51]
Add a page for managers that shows impact reports for whatever languages the manager selects. Allow the manager to filter for more recent reports. Make sure there is a button to export those reports as a PDF

**Comment by matt-t123** [comment]
Toby, I'm wondering whether exporting as excel sheet or some type of spreadsheet is actually more useful than exporting as PDF.  Maybe you have a reason for thinking of PDF?

**Comment by toby-1-kenobi** [comment]
I think it was just because I saw PDF in an email regarding this, maybe from Rachel. A spreadsheet might make more sense.
