### ISSUE TITLE
Unknown login form password icon

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#55]
**environment**: lcreporter-test
**priority of issue:** low
**impact of issue:**
Users might not understand what that icon means. There is no help text that explains what that icon means to the user. This icon should either be explained to the user or removed.

**Steps to reproduce**
1. Go to login page
2. Start typing in password text field and icon will appear

![login_icon](https://cloud.githubusercontent.com/assets/15933209/11385368/3a73f3ea-936c-11e5-8126-f21ed5048ed8.png)

**Comment by toby-1-kenobi** [comment]
This is not part of the app. It's added by the browser (are you using IE?) I think it's a control to unhide the password

**Comment by toby-1-kenobi** [comment]
This is not part of the app. It's added by the browser (are you using IE?) I think it's a control to unhide the password
