### ISSUE TITLE
No indication about page load or form submit

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#56]
**environment**: lcreporter-test
**priority of issue:** low
**issue reproducible in:** Chrome, IE 11

**impact of issue:**
Users accessing sag_reporter on browsers may not realise that a page load or form submit is occurring in the background. This may cause users to resubmit forms or click on a link again to force a page load since they do not realise something is actually occurring in the background. Most websites inform the user that some page load or form submit is actually occurring.

![page_loading_indicator](https://cloud.githubusercontent.com/assets/15933209/11385510/9e652670-936d-11e5-817a-57cbffc3ac52.png)

**Steps to reproduce**
1. Either login to the system or click on a menu item on home page
2. Notice that browser does not show that page load or form submit is in progress

**Comment by toby-1-kenobi** [comment]
I've put a spinner in now
