### ISSUE TITLE
[IMPORTANT] Cannot view reports by "Outcome Area" if report created with NO outcome areas selected

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#58]
**environment**: lcreporter-test (25th Nov)
**priority of issue:** Should be fixed ASAP
**issue reproducible in:** all browsers

**impact of issue:**
It affects ALL users attempting to view reports by outcome area. All users will be unable to view the report by outcome area unless the issue (with no outcome areas selected) is identified and deleted from the system (and not all users can do this). 

**Steps to reproduce**
1. Create a new report with _no_ outcome areas selected
2. Login as a user with privileges to view reports
3. Click "View all reports" from home page
4. Hover over "Group By" and select "Outcome Area"
![report_view](https://cloud.githubusercontent.com/assets/15933209/11386069/3d0cdbd4-9372-11e5-829c-c865d0c38016.png)

Page returns following error
![error](https://cloud.githubusercontent.com/assets/15933209/11386071/4133ee50-9372-11e5-8a35-fbfe3bbc034b.png)

**Comment by toby-1-kenobi** [comment]
fixed
