### ISSUE TITLE
Error when creating mother-tongue resource with 51+ character length contributer name

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#78]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** low
**impact of issue:**
I'm not sure how long (in character-length) the names of Indians (who are the main users of the system) are generally. In your test data the longest name I found was Abishek Aman kumar Dhurvey
(26 characters). Can names of Indian people go to 51 characters? I've decided to raise this issue just to get your feedback - please close this if this is an irrelevant issue. 

**Reproduction Steps**
1. Click "Report on a completed resource" from home page
2. In the contributers field enter input worth 50 characters (e.g. Abishek Aman kumar Dhurvey Abishek Aman kumar Dhas)
3. Submit the form. In this scenario no errors show
4. Repeat steps 1-2 again ... this time with input in the contributers field worth **51** characters (Abishek Aman kumar Dhurvey Abishek Aman kumar Dhas!)
5. Submit the form. In this scenario you get the following error message:

![rejected_change_error](https://cloud.githubusercontent.com/assets/15933209/11906478/00c1ee32-a621-11e5-8169-646246800596.png)

**Comment by toby-1-kenobi** [comment]
I need to check with managers about how long names can go. The length restriction is a sanity check (might prevent the wrong type of data entered here).

I any case the error should be more helpful.

**Comment by toby-1-kenobi** [comment]
fixed
