### ISSUE TITLE
Can only evaluate progress marker levels for the current year

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#81]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** medium

Is it always true that the managers will evaluate progress marker levels for that month in the current year? If so, then this is not a real issue and can be ignored.

![evaluate_progress](https://cloud.githubusercontent.com/assets/15933209/12044585/f7d47702-aee7-11e5-9a61-f01080dc0005.png)

**Comment by toby-1-kenobi** [comment]
I expect normal workflow will be that progress marker levels are evaluated for a month just finished. I can imagine people accidentally letting that slip for a few months, but not more than a year.
