### ISSUE TITLE
Cannot add new language

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#83]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** high
**impact of issue:**
Unable to add a new language means that it cannot be managed in sag_reporter. Users aren't able to do key functions (e.g. create new report, evaluate progress) in sag_reporter for a new language

**Reproduction Steps**
1. Login as a user with "Add another language" privileges
2. Click "View all languages" from main page
3. The page for "languages" does not show any ability to add a new language.

**Comment by toby-1-kenobi** [comment]
Thanks for the fix Silas!
