### ISSUE TITLE
Cannot add another outcome area (also known as "topic")

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#85]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** high
**impact of issue:**
Admins and managers are not be able to create new outcome areas in the system. 

**Reproduction Steps**
1. Login as a user with "View all topics" and "Add another topic" privileges
2. Select "View all outcome areas" from main page (viewable only if you have "View all topics" privileges)
3. The "View all outcome areas" page does not have any function for user to create a new outcome area.

**Comment by toby-1-kenobi** [comment]
This is as it should be. Outcome Areas are static, and shouldn't change.
