### ISSUE TITLE
Cannot edit an outcome area (also known as "topic")

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#86]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** high
**impact of issue:**
Admins and managers are not be able to edit outcome areas in the system. 

**Reproduction Steps**
1. Login as a user with "View all topics" and "Edit details about a topic" privileges
2. Select "View all outcome areas" from main page (viewable only if you have "View all topics" privileges)
3. The "View all outcome areas" page does not have any function for user to edit an existing outcome area.

**Comment by toby-1-kenobi** [comment]
Actually Outcome Areas are completely static and no-one should be able to edit them. The error is that the permission exists.
