### ISSUE TITLE
"Write another report" button shown on view report page for users without "Make new report" privileges

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#87]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** medium
**impact of issue:**
The system does enforce that users without "Make new report" can't create reports when they try to click this button. However users may believe that they have this privilege if they see this button. 

**Reproduction Steps**
1. Login as a user with "View all reports" permissions and does **NOT** have "Make a new report" privileges
2. Click "View all reports"
3. After the page has loaded, select any report to view
4. The "Write another report" appears when it shouldn't
5. Clicking on the "Write another report" takes the user to the main page

![edit_report_page](https://cloud.githubusercontent.com/assets/15933209/12316191/0ad4c09a-bad8-11e5-86db-11fa1e998264.png)

**Comment by toby-1-kenobi** [comment]
fixed by Silas
