### ISSUE TITLE
"Report on a completed resource" shows for user without such privileges

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#90]
**environment**: lcreporter-test (vr 0.14.4)
**priority of issue:** medium
**impact of issue:**
The system does enforce that users without "Add a new mother tongue resource" can't create resources when they click on "Report on a completed resource" from main page. However users may believe that they have this privilege if they see this option. 

**Reproduction Steps**
1. Login as a user **without** "Add a new mother tongue resource" permissions
2. "Report on a completed resource" option is shown on main page when it shouldn't
3. Clicking on this option reloads the main page again and does nothing.

**Comment by toby-1-kenobi** [comment]
Thanks for the fix Silas!
